// GENERATED by scripts/gen-teams.mjs from src/espn/fixtures/teams.json. Do not hand-edit.
// Source: https://site.api.espn.com/apis/site/v2/sports/football/nfl/teams?limit=40

export interface NflTeam {
  /** ESPN abbreviation, e.g. "BAL". Primary key for teams throughout the bot. */
  readonly abbr: string;
  readonly espnId: string;
  /** e.g. "Baltimore" */
  readonly location: string;
  /** e.g. "Ravens" — the label the requirements' message formats display. */
  readonly nickname: string;
  /** e.g. "Baltimore Ravens" */
  readonly displayName: string;
  /** ESPN logo URL, used once by scripts/upload-emojis.ts. */
  readonly logo: string;
}

export const TEAMS: readonly NflTeam[] = [
  { abbr: "ARI", espnId: "22", location: "Arizona", nickname: "Cardinals", displayName: "Arizona Cardinals", logo: "https://a.espncdn.com/i/teamlogos/nfl/500/ari.png" },
  { abbr: "ATL", espnId: "1", location: "Atlanta", nickname: "Falcons", displayName: "Atlanta Falcons", logo: "https://a.espncdn.com/i/teamlogos/nfl/500/atl.png" },
  { abbr: "BAL", espnId: "33", location: "Baltimore", nickname: "Ravens", displayName: "Baltimore Ravens", logo: "https://a.espncdn.com/i/teamlogos/nfl/500/bal.png" },
  { abbr: "BUF", espnId: "2", location: "Buffalo", nickname: "Bills", displayName: "Buffalo Bills", logo: "https://a.espncdn.com/i/teamlogos/nfl/500/buf.png" },
  { abbr: "CAR", espnId: "29", location: "Carolina", nickname: "Panthers", displayName: "Carolina Panthers", logo: "https://a.espncdn.com/i/teamlogos/nfl/500/car.png" },
  { abbr: "CHI", espnId: "3", location: "Chicago", nickname: "Bears", displayName: "Chicago Bears", logo: "https://a.espncdn.com/i/teamlogos/nfl/500/chi.png" },
  { abbr: "CIN", espnId: "4", location: "Cincinnati", nickname: "Bengals", displayName: "Cincinnati Bengals", logo: "https://a.espncdn.com/i/teamlogos/nfl/500/cin.png" },
  { abbr: "CLE", espnId: "5", location: "Cleveland", nickname: "Browns", displayName: "Cleveland Browns", logo: "https://a.espncdn.com/i/teamlogos/nfl/500/cle.png" },
  { abbr: "DAL", espnId: "6", location: "Dallas", nickname: "Cowboys", displayName: "Dallas Cowboys", logo: "https://a.espncdn.com/i/teamlogos/nfl/500/dal.png" },
  { abbr: "DEN", espnId: "7", location: "Denver", nickname: "Broncos", displayName: "Denver Broncos", logo: "https://a.espncdn.com/i/teamlogos/nfl/500/den.png" },
  { abbr: "DET", espnId: "8", location: "Detroit", nickname: "Lions", displayName: "Detroit Lions", logo: "https://a.espncdn.com/i/teamlogos/nfl/500/det.png" },
  { abbr: "GB", espnId: "9", location: "Green Bay", nickname: "Packers", displayName: "Green Bay Packers", logo: "https://a.espncdn.com/i/teamlogos/nfl/500/gb.png" },
  { abbr: "HOU", espnId: "34", location: "Houston", nickname: "Texans", displayName: "Houston Texans", logo: "https://a.espncdn.com/i/teamlogos/nfl/500/hou.png" },
  { abbr: "IND", espnId: "11", location: "Indianapolis", nickname: "Colts", displayName: "Indianapolis Colts", logo: "https://a.espncdn.com/i/teamlogos/nfl/500/ind.png" },
  { abbr: "JAX", espnId: "30", location: "Jacksonville", nickname: "Jaguars", displayName: "Jacksonville Jaguars", logo: "https://a.espncdn.com/i/teamlogos/nfl/500/jax.png" },
  { abbr: "KC", espnId: "12", location: "Kansas City", nickname: "Chiefs", displayName: "Kansas City Chiefs", logo: "https://a.espncdn.com/i/teamlogos/nfl/500/kc.png" },
  { abbr: "LAC", espnId: "24", location: "Los Angeles", nickname: "Chargers", displayName: "Los Angeles Chargers", logo: "https://a.espncdn.com/i/teamlogos/nfl/500/lac.png" },
  { abbr: "LAR", espnId: "14", location: "Los Angeles", nickname: "Rams", displayName: "Los Angeles Rams", logo: "https://a.espncdn.com/i/teamlogos/nfl/500/lar.png" },
  { abbr: "LV", espnId: "13", location: "Las Vegas", nickname: "Raiders", displayName: "Las Vegas Raiders", logo: "https://a.espncdn.com/i/teamlogos/nfl/500/lv.png" },
  { abbr: "MIA", espnId: "15", location: "Miami", nickname: "Dolphins", displayName: "Miami Dolphins", logo: "https://a.espncdn.com/i/teamlogos/nfl/500/mia.png" },
  { abbr: "MIN", espnId: "16", location: "Minnesota", nickname: "Vikings", displayName: "Minnesota Vikings", logo: "https://a.espncdn.com/i/teamlogos/nfl/500/min.png" },
  { abbr: "NE", espnId: "17", location: "New England", nickname: "Patriots", displayName: "New England Patriots", logo: "https://a.espncdn.com/i/teamlogos/nfl/500/ne.png" },
  { abbr: "NO", espnId: "18", location: "New Orleans", nickname: "Saints", displayName: "New Orleans Saints", logo: "https://a.espncdn.com/i/teamlogos/nfl/500/no.png" },
  { abbr: "NYG", espnId: "19", location: "New York", nickname: "Giants", displayName: "New York Giants", logo: "https://a.espncdn.com/i/teamlogos/nfl/500/nyg.png" },
  { abbr: "NYJ", espnId: "20", location: "New York", nickname: "Jets", displayName: "New York Jets", logo: "https://a.espncdn.com/i/teamlogos/nfl/500/nyj.png" },
  { abbr: "PHI", espnId: "21", location: "Philadelphia", nickname: "Eagles", displayName: "Philadelphia Eagles", logo: "https://a.espncdn.com/i/teamlogos/nfl/500/phi.png" },
  { abbr: "PIT", espnId: "23", location: "Pittsburgh", nickname: "Steelers", displayName: "Pittsburgh Steelers", logo: "https://a.espncdn.com/i/teamlogos/nfl/500/pit.png" },
  { abbr: "SEA", espnId: "26", location: "Seattle", nickname: "Seahawks", displayName: "Seattle Seahawks", logo: "https://a.espncdn.com/i/teamlogos/nfl/500/sea.png" },
  { abbr: "SF", espnId: "25", location: "San Francisco", nickname: "49ers", displayName: "San Francisco 49ers", logo: "https://a.espncdn.com/i/teamlogos/nfl/500/sf.png" },
  { abbr: "TB", espnId: "27", location: "Tampa Bay", nickname: "Buccaneers", displayName: "Tampa Bay Buccaneers", logo: "https://a.espncdn.com/i/teamlogos/nfl/500/tb.png" },
  { abbr: "TEN", espnId: "10", location: "Tennessee", nickname: "Titans", displayName: "Tennessee Titans", logo: "https://a.espncdn.com/i/teamlogos/nfl/500/ten.png" },
  { abbr: "WSH", espnId: "28", location: "Washington", nickname: "Commanders", displayName: "Washington Commanders", logo: "https://a.espncdn.com/i/teamlogos/nfl/500/wsh.png" },
];

/** All 32 teams play every week except those on a bye, so this is the bye-derivation baseline. */
export const TEAM_COUNT = TEAMS.length;

const BY_ABBR = new Map<string, NflTeam>(TEAMS.map((t) => [t.abbr, t]));

export function team(abbr: string): NflTeam {
  const found = BY_ABBR.get(abbr);
  if (!found) throw new Error(`Unknown NFL team abbreviation: ${abbr}`);
  return found;
}

export function isTeam(abbr: string): boolean {
  return BY_ABBR.has(abbr);
}

/** e.g. "Ravens" — used in schedule lines, pick options and recaps. */
export function nickname(abbr: string): string {
  return team(abbr).nickname;
}
