// Regenerates src/domain/teams.ts from the captured ESPN teams fixture.
// Run: node scripts/gen-teams.mjs
import fs from 'node:fs';

const raw = JSON.parse(fs.readFileSync('src/espn/fixtures/teams.json', 'utf8'));
const teams = raw.sports[0].leagues[0].teams
  .map((x) => x.team)
  .sort((a, b) => a.abbreviation.localeCompare(b.abbreviation));

const q = (s) => JSON.stringify(s);
const rows = teams
  .map(
    (t) =>
      `  { abbr: ${q(t.abbreviation)}, espnId: ${q(t.id)}, location: ${q(t.location)}, ` +
      `nickname: ${q(t.name)}, displayName: ${q(t.displayName)}, logo: ${q(t.logos?.[0]?.href ?? '')} },`
  )
  .join('\n');

const out = `// GENERATED by scripts/gen-teams.mjs from src/espn/fixtures/teams.json. Do not hand-edit.
// Source: https://site.api.espn.com/apis/site/v2/sports/football/nfl/teams?limit=40

export interface NflTeam {
  /** ESPN abbreviation, e.g. "BAL". Primary key for teams throughout the bot. */
  readonly abbr: string;
  readonly espnId: string;
  /** e.g. "Baltimore" */
  readonly location: string;
  /** e.g. "Ravens" — the label the requirements' message formats display. */
  readonly nickname: string;
  /** e.g. "Baltimore Ravens" */
  readonly displayName: string;
  /** ESPN logo URL, used once by scripts/upload-emojis.ts. */
  readonly logo: string;
}

export const TEAMS: readonly NflTeam[] = [
${rows}
];

/** All 32 teams play every week except those on a bye, so this is the bye-derivation baseline. */
export const TEAM_COUNT = TEAMS.length;

const BY_ABBR = new Map<string, NflTeam>(TEAMS.map((t) => [t.abbr, t]));

export function team(abbr: string): NflTeam {
  const found = BY_ABBR.get(abbr);
  if (!found) throw new Error(\`Unknown NFL team abbreviation: \${abbr}\`);
  return found;
}

export function isTeam(abbr: string): boolean {
  return BY_ABBR.has(abbr);
}

/** e.g. "Ravens" — used in schedule lines, pick options and recaps. */
export function nickname(abbr: string): string {
  return team(abbr).nickname;
}
`;

fs.writeFileSync('src/domain/teams.ts', out);
console.log(`wrote src/domain/teams.ts with ${teams.length} teams`);
